;;;======================================================================
;;;
;;; This file is generated by StringsCompress.pl from source in Strings.asm
;;; DO NOT EDIT DIRECTLY - See the maekfile for how to rebuild this file.
;;; This file only needs to be rebuilt if Strings.asm is changed.
;;;
;;;======================================================================

; Project name	:	XTIDE Universal BIOS
; Description	:	Strings and equates for BIOS messages.

%ifdef MODULE_STRINGS_COMPRESSED_PRECOMPRESS
%include "Display.inc"
%endif

; Section containing code
SECTION .text

; POST drive detection strings
g_szRomAt:
 db  034h, 020h, 0c6h, 039h, 01bh
; source:  25h, 73h, 20h, 40h, 20h, 25h, 78h, 0Ah, 0Dh, 00h

g_szMaster:
 db  053h, 067h, 079h, 07ah, 06bh, 0b8h
; source:  4Dh, 61h, 73h, 74h, 65h, 72h, 00h

g_szSlave:
 db  059h, 072h, 067h, 07ch, 06bh, 000h
; source:  53h, 6Ch, 61h, 76h, 65h, 20h, 00h

g_szDetect:
 db  04fh, 04ah, 0cbh, 034h, 020h, 067h, 0fah, 039h, 040h, 000h
; source:  49h, 44h, 45h, 20h, 25h, 73h, 20h, 61h, 74h, 20h, 25h, 78h, 3Ah, 20h, 00h



; Boot loader strings
g_szTryToBoot:
 db  048h, 075h, 075h, 07ah, 06fh, 074h, 0edh, 06ch, 078h, 075h, 0f3h, 034h, 020h, 039h, 024h, 039h, 01bh
; source:  42h, 6Fh, 6Fh, 74h, 69h, 6Eh, 67h, 20h, 66h, 72h, 6Fh, 6Dh, 20h, 25h, 73h, 20h, 25h, 78h, AFh, 25h, 78h, 0Ah, 0Dh, 00h

g_szBootSectorNotFound:
 db  048h, 075h, 075h, 0fah, 079h, 06bh, 069h, 07ah, 075h, 078h, 020h
; source:  42h, 6Fh, 6Fh, 74h, 20h, 73h, 65h, 63h, 74h, 6Fh, 72h, 20h

g_szNotFound:
 db  074h, 075h, 0fah, 06ch, 075h, 07bh, 074h, 06ah, 01bh
; source:  6Eh, 6Fh, 74h, 20h, 66h, 6Fh, 75h, 6Eh, 64h, 0Ah, 0Dh, 00h

g_szReadError:
 db  04bh, 078h, 078h, 075h, 0f8h, 039h, 025h, 01bh
; source:  45h, 72h, 72h, 6Fh, 72h, 20h, 25h, 78h, 21h, 0Ah, 0Dh, 00h


; Boot menu bottom of screen strings
g_szFDD:
 db  04ch, 04ah, 0cah, 020h, 020h, 020h, 000h
; source:  46h, 44h, 44h, 20h, 20h, 20h, 20h, 20h, 00h

g_szHDD:
 db  04eh, 04ah, 0cah, 020h, 020h, 020h, 000h
; source:  48h, 44h, 44h, 20h, 20h, 20h, 20h, 20h, 00h

g_szRomBoot:
 db  058h, 055h, 0d3h, 048h, 075h, 075h, 0bah
; source:  52h, 4Fh, 4Dh, 20h, 42h, 6Fh, 6Fh, 74h, 00h

g_szHotkey:
 db  03dh, 035h, 035h, 03dh, 034h, 03dh, 000h
; source:  25h, 41h, 25h, 63h, 25h, 63h, 25h, 41h, 25h, 73h, 25h, 41h, 20h, 00h



; Boot Menu menuitem strings
g_szDriveNum:
 db  039h, 000h
; source:  25h, 78h, 20h, 00h

g_szFDLetter:
 db  034h, 020h, 015h
; source:  25h, 73h, 20h, 25h, 63h, 00h

g_szFloppyDrv:
 db  04ch, 072h, 075h, 076h, 076h, 0ffh, 04ah, 078h, 06fh, 07ch, 0abh
; source:  46h, 6Ch, 6Fh, 70h, 70h, 79h, 20h, 44h, 72h, 69h, 76h, 65h, 00h

g_szforeignHD:
 db  04ch, 075h, 078h, 06bh, 06fh, 06dh, 0f4h, 04eh, 067h, 078h, 0eah, 04ah, 06fh, 079h, 0b1h
; source:  46h, 6Fh, 72h, 65h, 69h, 67h, 6Eh, 20h, 48h, 61h, 72h, 64h, 20h, 44h, 69h, 73h, 6Bh, 00h


; Boot Menu information strings
g_szCapacity:
 db  049h, 067h, 076h, 067h, 069h, 06fh, 07ah, 0ffh, 040h, 000h
; source:  43h, 61h, 70h, 61h, 63h, 69h, 74h, 79h, 20h, 3Ah, 20h, 00h

g_szSizeSingle:
 db  034h, 037h, 029h, 037h, 020h, 035h, 06fh, 088h
; source:  25h, 73h, 25h, 75h, 2Eh, 25h, 75h, 20h, 25h, 63h, 69h, 42h, 00h

g_szSizeDual:
 db  034h, 038h, 029h, 037h, 020h, 035h, 06fh, 0c8h, 02ah, 038h, 029h, 037h, 020h, 035h, 06fh, 048h, 01bh
; source:  25h, 73h, 25h, 35h, 2Dh, 75h, 2Eh, 25h, 75h, 20h, 25h, 63h, 69h, 42h, 20h, 2Fh, 25h, 35h, 2Dh, 75h, 2Eh, 25h, 75h, 20h, 25h, 63h, 69h, 42h, 0Ah, 0Dh, 00h

g_szCfgHeader:
 db  047h, 06ah, 06ah, 078h, 029h, 023h, 048h, 072h, 075h, 069h, 071h, 023h, 048h, 07bh, 079h, 023h, 04fh, 058h, 057h, 023h, 058h, 06bh, 079h, 06bh, 07ah, 01bh
; source:  41h, 64h, 64h, 72h, 2Eh, B3h, 42h, 6Ch, 6Fh, 63h, 6Bh, B3h, 42h, 75h, 73h, B3h, 49h, 52h, 51h, B3h, 52h, 65h, 73h, 65h, 74h, 0Ah, 0Dh, 00h

g_szCfgFormat:
 db  034h, 023h, 038h, 023h, 034h, 023h, 020h, 036h, 023h, 01ah
; source:  25h, 73h, B3h, 25h, 35h, 2Dh, 75h, B3h, 25h, 73h, B3h, 20h, 25h, 32h, 2Dh, 49h, B3h, 25h, 35h, 2Dh, 78h, 00h


g_szAddressingModes:					
g_szLCHS:
 db  052h, 028h, 049h, 04eh, 099h
; source:  4Ch, 2Dh, 43h, 48h, 53h, 00h

g_szPCHS:
 db  056h, 028h, 049h, 04eh, 099h
; source:  50h, 2Dh, 43h, 48h, 53h, 00h

g_szLBA28:
 db  052h, 048h, 047h, 02ch, 011h
; source:  4Ch, 42h, 41h, 32h, 38h, 00h

g_szLBA48:
 db  052h, 048h, 047h, 02eh, 011h
; source:  4Ch, 42h, 41h, 34h, 38h, 00h

g_szAddressingModes_Displacement equ (g_szPCHS - g_szAddressingModes)
;
; Ensure that addressing modes are correctly spaced in memory
;
%if g_szLCHS <> g_szAddressingModes
%error "g_szAddressingModes Displacement Incorrect 1"
%endif
%if g_szPCHS <> g_szLCHS + g_szAddressingModes_Displacement
%error "g_szAddressingModes Displacement Incorrect 2"
%endif
%if g_szLBA28 <> g_szPCHS + g_szAddressingModes_Displacement		
%error "g_szAddressingModes Displacement Incorrect 3"
%endif
%if g_szLBA48 <> g_szLBA28 + g_szAddressingModes_Displacement		
%error "g_szAddressingModes Displacement Incorrect 4"
%endif				

g_szFddUnknown:
 db  034h, 05bh, 074h, 071h, 074h, 075h, 07dh, 0b4h
; source:  25h, 73h, 55h, 6Eh, 6Bh, 6Eh, 6Fh, 77h, 6Eh, 00h

g_szFddSizeOr:
 db  034h, 02fh, 021h, 026h, 020h, 075h, 0f8h, 02dh, 022h, 026h, 020h, 04ah, 08ah
; source:  25h, 73h, 35h, ACh, 22h, 20h, 6Fh, 72h, 20h, 33h, ABh, 22h, 20h, 44h, 44h, 00h

g_szFddSize:
 db  034h, 034h, 026h, 027h, 020h, 037h, 020h, 071h, 06fh, 088h
; source:  25h, 73h, 25h, 73h, 22h, 2Ch, 20h, 25h, 75h, 20h, 6Bh, 69h, 42h, 00h


g_szFddThreeHalf:
 db  02dh, 002h
; source:  33h, ABh, 00h

g_szFddFiveQuarter:
 db  02fh, 001h
; source:  35h, ACh, 00h

g_szFddThreeFive_Displacement equ (g_szFddFiveQuarter - g_szFddThreeHalf)

g_szBusTypeValues:		
g_szBusTypeValues_8Dual:
 db  04ah, 031h, 000h
; source:  44h, 38h, 20h, 00h

g_szBusTypeValues_8Reversed:
 db  05eh, 031h, 000h
; source:  58h, 38h, 20h, 00h

g_szBusTypeValues_8Single:
 db  059h, 031h, 000h
; source:  53h, 38h, 20h, 00h

g_szBusTypeValues_16:
 db  020h, 02bh, 010h
; source:  20h, 31h, 36h, 00h

g_szBusTypeValues_32:
 db  020h, 02dh, 00ch
; source:  20h, 33h, 32h, 00h

g_szBusTypeValues_Serial:
 db  059h, 04bh, 098h
; source:  53h, 45h, 52h, 00h

g_szBusTypeValues_Displacement equ (g_szBusTypeValues_8Reversed - g_szBusTypeValues)
;
; Ensure that bus type strings are correctly spaced in memory
;
%if g_szBusTypeValues_8Dual <> g_szBusTypeValues
%error "g_szBusTypeValues Displacement Incorrect 1"
%endif
%if g_szBusTypeValues_8Reversed <> g_szBusTypeValues + g_szBusTypeValues_Displacement
%error "g_szBusTypeValues Displacement Incorrect 2"		
%endif
%if g_szBusTypeValues_8Single <> g_szBusTypeValues_8Reversed + g_szBusTypeValues_Displacement
%error "g_szBusTypeValues Displacement Incorrect 3"				
%endif
%if g_szBusTypeValues_16 <> g_szBusTypeValues_8Single + g_szBusTypeValues_Displacement		
%error "g_szBusTypeValues Displacement Incorrect 4"				
%endif
%if g_szBusTypeValues_32 <> g_szBusTypeValues_16 + g_szBusTypeValues_Displacement
%error "g_szBusTypeValues Displacement Incorrect 5"				
%endif
%if g_szBusTypeValues_Serial <> g_szBusTypeValues_32 + g_szBusTypeValues_Displacement
%error "g_szBusTypeValues Displacement Incorrect 6"				
%endif				

g_szSelectionTimeout:
 db  032h, 033h, 03dh, 059h, 06bh, 072h, 06bh, 069h, 07ah, 06fh, 075h, 0f4h, 06fh, 0f4h, 03ch, 020h, 0b9h
; source:  C8h, B5h, 25h, 41h, 53h, 65h, 6Ch, 65h, 63h, 74h, 69h, 6Fh, 6Eh, 20h, 69h, 6Eh, 20h, 25h, 32h, 2Dh, 75h, 20h, 73h, 00h


g_szDashForZero:
 db  028h, 000h
; source:  2Dh, 20h, 00h

StringsCompressed_NormalBase equ 58

;; translated usage stats
;; 179:8
;; 50:2
;; 32:33
;; 51:3
;; 33:1
;; 52:1
;; 34:3
;; 53:2
;; 44:1
;; 54:1
;; 45:3
;; 46:4
;; 56:5
;; 47:1
;; 49:1
;; 200:1
;; 171:2
;; 181:1
;; 172:2
;; 175:1
;; total special: 20
StringsCompressed_TranslatesAndFormats: 
        db     32  ; 0
        db     172  ; 1
        db     171  ; 2
        db     179  ; 3
        db     175  ; 4
        db     33  ; 5
        db     34  ; 6
        db     44  ; 7
        db     45  ; 8
        db     46  ; 9
        db     47  ; 10
        db     49  ; 11
        db     50  ; 12
        db     51  ; 13
        db     52  ; 14
        db     53  ; 15
        db     54  ; 16
        db     56  ; 17
        db     200  ; 18
        db     181  ; 19

;; format usage stats
;; A:4
;; c:6
;; s:13
;; 2-u:1
;; u:5
;; 5-u:3
;; 2-I:1
;; x:6
;; 5-x:1
;; nl:6
;; total format: 10
        db     (DisplayFormatCompressed_BaseFormatOffset - DisplayFormatCompressed_Format_s)  ; 20
        db     (DisplayFormatCompressed_BaseFormatOffset - DisplayFormatCompressed_Format_c)  ; 21
        db     (DisplayFormatCompressed_BaseFormatOffset - DisplayFormatCompressed_Format_2_I)  ; 22
        db     (DisplayFormatCompressed_BaseFormatOffset - DisplayFormatCompressed_Format_u)  ; 23
        db     (DisplayFormatCompressed_BaseFormatOffset - DisplayFormatCompressed_Format_5_u)  ; 24
        db     (DisplayFormatCompressed_BaseFormatOffset - DisplayFormatCompressed_Format_x)  ; 25
        db     (DisplayFormatCompressed_BaseFormatOffset - DisplayFormatCompressed_Format_5_x)  ; 26
        db     (DisplayFormatCompressed_BaseFormatOffset - DisplayFormatCompressed_Format_nl)  ; 27
        db     (DisplayFormatCompressed_BaseFormatOffset - DisplayFormatCompressed_Format_2_u)  ; 28
        db     (DisplayFormatCompressed_BaseFormatOffset - DisplayFormatCompressed_Format_A)  ; 29

StringsCompressed_FormatsBegin   equ   20


;; alphabet usage stats
;; 58,::2
;; 59,;:
;; 60,<:
;; 61,=:
;; 62,>:
;; 63,?:
;; 64,@:1
;; 65,A:3
;; 66,B:11
;; 67,C:3
;; 68,D:10
;; 69,E:3
;; 70,F:3
;; 71,G:
;; 72,H:4
;; 73,I:2
;; 74,J:
;; 75,K:
;; 76,L:3
;; 77,M:2
;; 78,N:
;; 79,O:1
;; 80,P:1
;; 81,Q:1
;; 82,R:4
;; 83,S:6
;; 84,T:
;; 85,U:1
;; 86,V:
;; 87,W:
;; 88,X:1
;; 89,Y:
;; 90,Z:
;; 91,[:
;; 92,\:
;; 93,]:
;; 94,^:
;; 95,_:
;; 96,`:
;; 97,a:6
;; 98,b:
;; 99,c:4
;; 100,d:4
;; 101,e:9
;; 102,f:2
;; 103,g:2
;; 104,h:
;; 105,i:11
;; 106,j:
;; 107,k:4
;; 108,l:4
;; 109,m:1
;; 110,n:9
;; 111,o:17
;; 112,p:3
;; 113,q:
;; 114,r:11
;; 115,s:6
;; 116,t:10
;; 117,u:2
;; 118,v:2
;; 119,w:1
;; 120,x:
;; 121,y:2
;; alphabet used_count: 39
